import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Shubh Gupta | Software & ML Engineer Portfolio</title>
        <meta name="description" content="Shubh Gupta’s full-stack portfolio: ML, blockchain, data, and web projects. Explore 15 impactful projects and résumé." />
        <meta property="og:title" content="Shubh Gupta Portfolio" />
        <meta property="og:description" content="Showcasing ML, blockchain, and web projects. Explore 15 impactful projects and résumé." />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="/profile.jpg" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
